# Generated by Django 3.1.1 on 2020-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
