# Generated by Django 3.1.1 on 2020-09-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200928_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_picture',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
