# Generated by Django 3.1.1 on 2020-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200928_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
