# Generated by Django 3.1.1 on 2020-09-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200928_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
